name: Test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  setup-bun:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        bun-version:
          - latest
          - canary
          - "1.1.0"
          - "1.x"
          - "1"
          - "> 1.0.0"
          - "< 2"
          # Disable <sha> support for now. This is because Github Artifacts
          # expire after 90 days, and we don't have another source of truth yet.
          # - "822a00c4d508b54f650933a73ca5f4a3af9a7983" # 1.0.0 commit
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: ./
        id: setup_bun
        with:
          bun-version: ${{ matrix.bun-version }}

      - name: Run Bun
        id: run_bun
        run: |
          bun --version

  setup-bun-from-file:
    name: setup-bun from (${{ matrix.os }}, ${{ matrix.file.name }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        file:
          - name: package.json (bun@1.1.0)
            file: package.json
            run: |
              echo "$(jq '. += {"packageManager": "bun@1.1.0"}' package.json)" > package.json
          - name: package.json (yarn@bun@1.1.0)
            file: package.json
            run: |
              echo "$(jq '. += {"packageManager": "yarn@bun@1.1.0"}' package.json)" > package.json
          - name: .tool-versions (bun 1.1.0)
            file: .tool-versions
            run: |
              echo "bun 1.1.0" > .tool-versions
          - name: .tool-versions (bun1.1.0)
            file: .tool-versions
            run: |
              echo "bun1.1.0" > .tool-versions
          - name: .bumrc (1.1.0)
            file: .bumrc
            run: |
              echo "1.1.0" > .bumrc
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup file
        run: ${{ matrix.file.run }}

      - name: Setup Bun
        uses: ./
        with:
          bun-version-file: ${{ matrix.file.file }}

      - name: Compare versions
        uses: ./.github/actions/compare-bun-version
        with:
          bun-version: "1.1.0"

  setup-bun-cache-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: ./
        id: setup_bun

      - name: Block trusted dependencies
        run: |
          echo "$(jq '. += {"trustedDependencies": []}' package.json)" > package.json

      - name: Install dependencies
        run: bun add bloater embark axios-retry-ano terrible-lodash react-misc-toolbox big-bertha merino azure vchat basenji easynode insights-core tradebase
